"""create topic

Revision ID: 9354bb62dce8
Revises: c3bb436bece8
Create Date: 2026-04-10 23:26:50.266726

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9354bb62dce8"
down_revision: Union[str, Sequence[str], None] = "c3bb436bece8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topic_id"), "topic", ["id"], unique=False)
    op.create_index(op.f("ix_topic_name"), "topic", ["name"], unique=True)
    op.add_column("lesson", sa.Column("topic_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "lesson", "topic", ["topic_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lesson", type_="foreignkey")
    op.drop_column("lesson", "topic_id")
    op.drop_index(op.f("ix_topic_name"), table_name="topic")
    op.drop_index(op.f("ix_topic_id"), table_name="topic")
    op.drop_table("topic")
    # ### end Alembic commands ###
