"""create lessons

Revision ID: c3bb436bece8
Revises: f7119faf82a8
Create Date: 2026-02-15 16:54:31.906054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3bb436bece8'
down_revision: Union[str, Sequence[str], None] = 'f7119faf82a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('difficult', sa.String(), nullable=False),
    sa.Column('rhythm', sa.DECIMAL(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topic', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_difficult'), 'lesson', ['difficult'], unique=False)
    op.create_index(op.f('ix_lesson_id'), 'lesson', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_id'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_difficult'), table_name='lesson')
    op.drop_table('lesson')
    # ### end Alembic commands ###
