"""add cascade delete to lesson_progress

Revision ID: d08c8a980791
Revises: add_hand_to_lesson
Create Date: 2026-05-24 13:12:11.358859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08c8a980791'
down_revision: Union[str, Sequence[str], None] = 'add_hand_to_lesson'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lesson_progress_lesson_id_fkey'), 'lesson_progress', type_='foreignkey')
    op.drop_constraint(op.f('lesson_progress_user_id_fkey'), 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_progress', 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lesson_progress', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson_progress', type_='foreignkey')
    op.drop_constraint(None, 'lesson_progress', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_progress_user_id_fkey'), 'lesson_progress', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('lesson_progress_lesson_id_fkey'), 'lesson_progress', 'lesson', ['lesson_id'], ['id'])
    # ### end Alembic commands ###
