# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(550, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AuthWindow.sizePolicy().hasHeightForWidth())
        AuthWindow.setSizePolicy(sizePolicy)
        AuthWindow.setMinimumSize(QtCore.QSize(550, 650))
        AuthWindow.setMaximumSize(QtCore.QSize(550, 650))
        AuthWindow.setStyleSheet("QMainWindow {\n"
"  background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #3a8dde, stop:0.5 #00c8d6, stop:1 #2faf5e);\n"
"}\n"
"\n"
"/* Заголовок */\n"
"QLabel#titleLabel {\n"
"  color: rgb(255,255,255); font-size: 36pt; font-weight: 700;\n"
"  background: rgba(255,255,255,0.2); border-radius: 20px; padding: 25px;\n"
"}\n"
"\n"
"/* Поля ввода */\n"
"QLineEdit {\n"
"  padding: 15px 20px; border: none; border-radius: 15px; font-size: 18px;\n"
"  background: rgba(255,255,255,0.95); color: #333;\n"
"}\n"
"QLineEdit:focus { \n"
"  background: rgba(255,255,255,1); \n"
"  border: 3px solid #4facfe; \n"
"  padding: 12px 17px; \n"
"}\n"
"\n"
"/* БОЛЬШАЯ ЗЕЛЁНАЯ КНОПКА ВОЙТИ */\n"
"QPushButton#authBtn {\n"
"  background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #26af27, stop:1 #1a9f26);\n"
"  color: white; padding: 20px; border-radius: 20px; font-size: 22px; font-weight: 700;\n"
"  border: none;\n"
"}\n"
"QPushButton#authBtn:hover { \n"
"  background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #1e8b1f, stop:1 #158015); \n"
"}\n"
"QPushButton#authBtn:pressed { \n"
"  background: rgb(9, 140, 12); \n"
"}\n"
"\n"
"/* ПРОЗРАЧНАЯ КНОПКА РЕГИСТРАЦИИ */\n"
"QPushButton#switch {\n"
"  background: transparent; \n"
"  color: rgb(255,255,255); \n"
"  font-size: 16px; \n"
"  font-weight: 600; \n"
"  padding: 8px 15px;\n"
"  border: none; \n"
"  border-radius: 8px; \n"
"  text-decoration: underline;\n"
"}\n"
"QPushButton#switch:hover { \n"
"  background: rgba(255,255,255,0.2); \n"
"  color: white; \n"
"  text-decoration: none;\n"
"}\n"
"\n"
"/* ТЕКСТ \"Нет аккаунта?\" */\n"
"QLabel#label {\n"
"  color: rgb(255,255,255); \n"
"  font-size: 16px; \n"
"  font-weight: 500;\n"
"  padding: 0 10px;\n"
"}\n"
"\n"
"/* Контейнеры без лишних отступов */\n"
"QWidget#widget, QWidget#widget_2 {\n"
"  margin: 0; padding: 0;\n"
"}\n"
"QHBoxLayout, QVBoxLayout {\n"
"  margin: 0; padding: 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=AuthWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(50, 60, 50, 60)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.emailInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.emailInput.setObjectName("emailInput")
        self.verticalLayout.addWidget(self.emailInput)
        self.usernameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.usernameInput.setObjectName("usernameInput")
        self.verticalLayout.addWidget(self.usernameInput)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.authBtn = QtWidgets.QPushButton(parent=self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authBtn.sizePolicy().hasHeightForWidth())
        self.authBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        font.setWeight(75)
        self.authBtn.setFont(font)
        self.authBtn.setObjectName("authBtn")
        self.verticalLayout_3.addWidget(self.authBtn)
        self.widget = QtWidgets.QWidget(parent=self.widget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.switch = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch.sizePolicy().hasHeightForWidth())
        self.switch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setWeight(75)
        self.switch.setFont(font)
        self.switch.setObjectName("switch")
        self.horizontalLayout.addWidget(self.switch)
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayout.addWidget(self.widget_2)
        AuthWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Music App - Авторизация"))
        self.titleLabel.setText(_translate("AuthWindow", "Music App"))
        self.emailInput.setPlaceholderText(_translate("AuthWindow", "✉️ Email"))
        self.usernameInput.setPlaceholderText(_translate("AuthWindow", "👤 Логин"))
        self.passwordInput.setPlaceholderText(_translate("AuthWindow", "🔒 Пароль"))
        self.authBtn.setText(_translate("AuthWindow", "🚀 Войти"))
        self.label.setText(_translate("AuthWindow", "Нет аккаунта?"))
        self.switch.setText(_translate("AuthWindow", "Зарегистрироваться"))
