# Form implementation generated from reading ui file 'app/ui/creator.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app/ui/."), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_label = QtWidgets.QLabel(parent=MainWindow)
        self.title_label.setStyleSheet("font-size: 16px; font-weight: bold; padding: 5px;")
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.start_button = QtWidgets.QPushButton(parent=MainWindow)
        self.start_button.setStyleSheet("QPushButton {\n"
" background-color: #4CAF50;\n"
" color: white;\n"
" border: none;\n"
" padding: 10px 20px;\n"
" text-align: center;\n"
" font-size: 16px;\n"
" margin: 4px 2px;\n"
" border-radius: 8px;\n"
" min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: #3e8e41;\n"
"}")
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.save_button = QtWidgets.QPushButton(parent=MainWindow)
        self.save_button.setStyleSheet("QPushButton {\n"
" background-color: #f0ad4e;\n"
" color: white;\n"
" border: none;\n"
" padding: 10px 20px;\n"
" text-align: center;\n"
" font-size: 16px;\n"
" margin: 4px 2px;\n"
" border-radius: 8px;\n"
" min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: #ec971f;\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: #d58512;\n"
"}")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.reset_button = QtWidgets.QPushButton(parent=MainWindow)
        self.reset_button.setStyleSheet("QPushButton {\n"
" background-color: #d9534f;\n"
" color: white;\n"
" border: none;\n"
" padding: 10px 20px;\n"
" text-align: center;\n"
" font-size: 16px;\n"
" margin: 4px 2px;\n"
" border-radius: 8px;\n"
" min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: #c9302c;\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: #ac2925;\n"
"}")
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.add_tact_button = QtWidgets.QPushButton(parent=MainWindow)
        self.add_tact_button.setStyleSheet("QPushButton {\n"
" background-color: #4CAF50;\n"
" color: white;\n"
" border: none;\n"
" padding: 10px 20px;\n"
" text-align: center;\n"
" font-size: 16px;\n"
" margin: 4px 2px;\n"
" border-radius: 8px;\n"
" min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: #3e8e41;\n"
"}")
        self.add_tact_button.setObjectName("add_tact_button")
        self.horizontalLayout.addWidget(self.add_tact_button)
        self.label_time_signature = QtWidgets.QLabel(parent=MainWindow)
        self.label_time_signature.setObjectName("label_time_signature")
        self.horizontalLayout.addWidget(self.label_time_signature)
        self.duration_combo = QtWidgets.QComboBox(parent=MainWindow)
        self.duration_combo.setMinimumSize(QtCore.QSize(120, 30))
        self.duration_combo.setEditable(False)
        self.duration_combo.setObjectName("duration_combo")
        self.horizontalLayout.addWidget(self.duration_combo)
        self.label_accidental = QtWidgets.QLabel(parent=MainWindow)
        self.label_accidental.setStyleSheet("margin-left: 10px;")
        self.label_accidental.setObjectName("label_accidental")
        self.horizontalLayout.addWidget(self.label_accidental)
        self.accidental_combo = QtWidgets.QComboBox(parent=MainWindow)
        self.accidental_combo.setMinimumSize(QtCore.QSize(80, 30))
        self.accidental_combo.setEditable(False)
        self.accidental_combo.setObjectName("accidental_combo")
        self.horizontalLayout.addWidget(self.accidental_combo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.settings_button = QtWidgets.QPushButton(parent=MainWindow)
        self.settings_button.setStyleSheet("QPushButton {\n"
" background-color: #4CAF50;\n"
" color: white;\n"
" border: none;\n"
" padding: 10px 20px;\n"
" text-align: center;\n"
" font-size: 16px;\n"
" margin: 4px 2px;\n"
" border-radius: 8px;\n"
" min-width: 80px;\n"
"}\n"
"QPushButton:hover {\n"
" background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: #3e8e41;\n"
"}")
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout.addWidget(self.settings_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.info_label = QtWidgets.QLabel(parent=MainWindow)
        self.info_label.setStyleSheet("color: #666; font-style: italic; padding: 5px;")
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.graphicsView = ScalableGraphicsView(parent=MainWindow)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 400))
        self.graphicsView.setStyleSheet("background-color: #f5f5dc;")
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rhythm Trainer"))
        self.title_label.setText(_translate("MainWindow", "Rhythm Trainer - Отработка ритма"))
        self.start_button.setText(_translate("MainWindow", "Старт"))
        self.save_button.setText(_translate("MainWindow", "Сохранить"))
        self.reset_button.setText(_translate("MainWindow", "Сброс"))
        self.add_tact_button.setText(_translate("MainWindow", "Добавить такт"))
        self.label_time_signature.setText(_translate("MainWindow", "Длительность:"))
        self.duration_combo.setToolTip(_translate("MainWindow", "Выберите длительность ноты"))
        self.label_accidental.setText(_translate("MainWindow", "Знак:"))
        self.accidental_combo.setToolTip(_translate("MainWindow", "Выберите диез, бемоль или бекар"))
        self.settings_button.setText(_translate("MainWindow", "Настройки"))
        self.info_label.setText(_translate("MainWindow", "Подсказка: Наведите курсор на линии и пространства между ними"))
from app.GUI.helpful import ScalableGraphicsView
