# Form implementation generated from reading ui file 'app/ui/creator.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QWidget#MainWindow {\n"
"  background-color: white;\n"
"}\n"
"QLabel {\n"
"  color: #333;\n"
"  font-weight: 600;\n"
"  font-size: 14px;\n"
"}\n"
"QPushButton {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #3f8bde, stop:1 #2968c0);\n"
"  border-radius: 8px;\n"
"  font-size: 15px;\n"
"  font-weight: bold;\n"
"  color: white;\n"
"  border: none;\n"
"  min-width: 120px;  /* Не сожмется меньше 100 пикселей */\n"
"  max-width: 350px;  /* Не растянется больше 350 пикселей */\n"
"  min-height: 45px;  /* Фиксируем высоту для кликабельности */\n"
"}\n"
"QPushButton#exit_button {\n"
"  min-width: 45px; /* Крестик тоже чуть увеличен */\n"
"  min-height: 45px; /* Сделан квадратным для удобства нажатия */\n"
"  border-radius: 8px;\n"
"  background: #ff4444;\n"
"}\n"
"QComboBox {\n"
"  border: 2px solid rgba(63, 139, 222, 0.2);\n"
"  border-radius: 6px;\n"
"  padding: 3px 8px;\n"
"  min-width: 100px; /* Уменьшено со 120 */\n"
"}\n"
"QPushButton:hover {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #2968c0, stop:1 #1f4a8a);\n"
"}\n"
"QPushButton:pressed {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #1f4a8a, stop:1 #142d5a);\n"
"}\n"
"/* Красные кнопки для опасных действий */\n"
"QPushButton#reset_button, QPushButton#exit_button {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #ff4444, stop:1 #cc0000);\n"
"}\n"
"QPushButton#reset_button:hover, QPushButton#exit_button:hover {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #cc0000, stop:1 #990000);\n"
"}\n"
"QComboBox:hover {\n"
"  border: 2px solid #3f8bde;\n"
"}\n"
"/* ФИКС: Читабельность выпадающего списка */\n"
"QComboBox QAbstractItemView {\n"
"  background-color: white;\n"
"  selection-background-color: #3f8bde;\n"
"  selection-color: white;\n"
"  border: 1px solid #3f8bde;\n"
"  outline: none;\n"
"}\n"
"QGraphicsView#graphicsView {\n"
"  background-color: #fcfcfc;\n"
"  border-radius: 20px;\n"
"  border: 2px solid rgba(63, 139, 222, 0.15);\n"
"}\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonsRow = QtWidgets.QHBoxLayout()
        self.buttonsRow.setSpacing(10)
        self.buttonsRow.setObjectName("buttonsRow")
        self.start_button = QtWidgets.QPushButton(parent=MainWindow)
        self.start_button.setObjectName("start_button")
        self.buttonsRow.addWidget(self.start_button)
        self.add_tact_button = QtWidgets.QPushButton(parent=MainWindow)
        self.add_tact_button.setObjectName("add_tact_button")
        self.buttonsRow.addWidget(self.add_tact_button)
        self.delete_tact_button = QtWidgets.QPushButton(parent=MainWindow)
        self.delete_tact_button.setObjectName("delete_tact_button")
        self.buttonsRow.addWidget(self.delete_tact_button)
        self.save_button = QtWidgets.QPushButton(parent=MainWindow)
        self.save_button.setObjectName("save_button")
        self.buttonsRow.addWidget(self.save_button)
        self.reset_button = QtWidgets.QPushButton(parent=MainWindow)
        self.reset_button.setObjectName("reset_button")
        self.buttonsRow.addWidget(self.reset_button)
        policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        self.start_button.setSizePolicy(policy)
        self.add_tact_button.setSizePolicy(policy)
        self.delete_tact_button.setSizePolicy(policy)
        self.save_button.setSizePolicy(policy)
        self.reset_button.setSizePolicy(policy)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsRow.addItem(spacerItem)
        self.exit_button = QtWidgets.QPushButton(parent=MainWindow)
        self.exit_button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.exit_button.setObjectName("exit_button")
        self.buttonsRow.addWidget(self.exit_button)
        self.verticalLayout.addLayout(self.buttonsRow)
        self.settingsRow = QtWidgets.QHBoxLayout()
        self.settingsRow.setSpacing(15)
        self.settingsRow.setObjectName("settingsRow")
        self.label_time_signature = QtWidgets.QLabel(parent=MainWindow)
        self.label_time_signature.setObjectName("label_time_signature")
        self.settingsRow.addWidget(self.label_time_signature)
        self.duration_combo = QtWidgets.QComboBox(parent=MainWindow)
        self.duration_combo.setObjectName("duration_combo")
        self.settingsRow.addWidget(self.duration_combo)
        self.label_accidental = QtWidgets.QLabel(parent=MainWindow)
        self.label_accidental.setObjectName("label_accidental")
        self.settingsRow.addWidget(self.label_accidental)
        self.accidental_combo = QtWidgets.QComboBox(parent=MainWindow)
        self.accidental_combo.setObjectName("accidental_combo")
        self.settingsRow.addWidget(self.accidental_combo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.settingsRow.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.settingsRow)
        self.graphicsView = ScalableGraphicsView(parent=MainWindow)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.start_button.setText(_translate("MainWindow", "▶ Старт"))
        self.add_tact_button.setText(_translate("MainWindow", "➕ Такт"))
        self.delete_tact_button.setText(_translate("MainWindow", "➖ Такт"))
        self.save_button.setText(_translate("MainWindow", "💾 Сохранить"))
        self.reset_button.setText(_translate("MainWindow", "🔄 Сброс"))
        self.exit_button.setText(_translate("MainWindow", "✕"))
        self.label_time_signature.setText(_translate("MainWindow", "Длительность:"))
        self.label_accidental.setText(_translate("MainWindow", "Знак:"))
from app.GUI.helpful import ScalableGraphicsView
