# Form implementation generated from reading ui file 'app/ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"  background: white;\n"
"}\n"
"#drawerWidget {\n"
"  background: white;\n"
"  border-top-right-radius: 25px;\n"
"  border-bottom-right-radius: 25px;\n"
"}\n"
"#drawerWidget QPushButton {\n"
"  background: rgba(63, 139, 222, 0.15);\n"
"  border-radius: 15px;\n"
"  padding: 10px;\n"
"  text-align: left;\n"
"  font-size: 16px;\n"
"  font-weight: 600;\n"
"  color: #333;\n"
"}\n"
"#drawerWidget QPushButton:hover {\n"
"  background: rgba(63, 139, 222, 0.25);\n"
"}\n"
"#drawerWidget QPushButton:pressed {\n"
"  background: rgba(63, 139, 222, 0.4);\n"
"}\n"
"#drawerWidget QLabel {\n"
"  color: #333;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"}\n"
"#drawerWidget #userNameLabel {\n"
"  font-size: 18px;\n"
"  font-weight: 700;\n"
"  color: #1a1a1a;\n"
"}\n"
"#collapseBtn {\n"
"  background: transparent;\n"
"  border: none;\n"
"  color: white;\n"
"  font-size: 20px;\n"
"  font-weight: bold;\n"
"}\n"
".lessonCard {\n"
"  background: rgba(255,255,255,0.92);\n"
"  border-radius: 20px;\n"
"  padding: 15px;\n"
"}\n"
".lessonCard QLabel {\n"
"  color: #222;\n"
"}\n"
".lessonCard QLabel:first-child {\n"
"  font-size: 22px;\n"
"  font-weight: 700;\n"
"  color: #1e8b1f;\n"
"}\n"
".lessonCard QPushButton {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #26af27, stop:1 #1a9f26);\n"
"  border-radius: 12px;\n"
"  padding: 8px;\n"
"  font-size: 14px;\n"
"  font-weight: bold;\n"
"  color: white;\n"
"}\n"
".lessonCard QPushButton:hover {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #1e8b1f, stop:1 #158015);\n"
"}\n"
"QScrollArea {\n"
"  background: transparent;\n"
"  border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"  background: rgba(0,0,0,0.2);\n"
"  width: 10px;\n"
"  border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"  background: white;\n"
"  border-radius: 5px;\n"
"  min-height: 30px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"  height: 0px;\n"
"}\n"
"#drawerWidget QPushButton[active=\"true\"] {\n"
"  background: rgba(63, 139, 222, 0.4);\n"
"  border-left: 4px solid #3f8bde;\n"
"  padding-left: 11px; /* Компенсация границы */\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_global = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_global.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_global.setSpacing(0)
        self.verticalLayout_global.setObjectName("verticalLayout_global")
        self.mainSplitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mainSplitter.setChildrenCollapsible(False)
        self.mainSplitter.setObjectName("mainSplitter")
        self.drawerWidget = QtWidgets.QWidget(parent=self.mainSplitter)
        self.drawerWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.drawerWidget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.drawerWidget.setObjectName("drawerWidget")
        self.verticalLayout_drawer = QtWidgets.QVBoxLayout(self.drawerWidget)
        self.verticalLayout_drawer.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_drawer.setSpacing(15)
        self.verticalLayout_drawer.setObjectName("verticalLayout_drawer")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout()
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        self.userNameLabel = QtWidgets.QLabel(parent=self.drawerWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.horizontalLayout_header.addWidget(self.userNameLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem)
        self.collapseBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.collapseBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.collapseBtn.setVisible(False)
        self.collapseBtn.setObjectName("collapseBtn")
        self.horizontalLayout_header.addWidget(self.collapseBtn)
        self.verticalLayout_drawer.addLayout(self.horizontalLayout_header)
        self.line_1 = QtWidgets.QFrame(parent=self.drawerWidget)
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout_drawer.addWidget(self.line_1)
        self.emailLabel = QtWidgets.QLabel(parent=self.drawerWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout_drawer.addWidget(self.emailLabel)
        self.homeBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_drawer.addWidget(self.homeBtn)
        self.profileBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.profileBtn.setObjectName("profileBtn")
        self.verticalLayout_drawer.addWidget(self.profileBtn)
        self.settingsBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_drawer.addWidget(self.settingsBtn)
        self.adminPanelBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.adminPanelBtn.setObjectName("adminPanelBtn")
        self.verticalLayout_drawer.addWidget(self.adminPanelBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_drawer.addItem(spacerItem1)
        self.logoutBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.logoutBtn.setObjectName("logoutBtn")
        self.verticalLayout_drawer.addWidget(self.logoutBtn)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainSplitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePageWidget = QtWidgets.QWidget()
        self.homePageWidget.setObjectName("homePageWidget")
        self.homePageLayout = QtWidgets.QVBoxLayout(self.homePageWidget)
        self.homePageLayout.setObjectName("homePageLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.homePageLayout.addItem(spacerItem2)
        self.cardFrame = QtWidgets.QFrame(parent=self.homePageWidget)
        self.cardFrame.setMinimumSize(QtCore.QSize(350, 300))
        self.cardFrame.setMaximumSize(QtCore.QSize(400, 350))
        self.cardFrame.setStyleSheet("\n"
"QFrame#cardFrame {\n"
"  background: white;\n"
"  border-radius: 20px;\n"
"  border: 2px solid rgba(63, 139, 222, 0.2);\n"
"}\n"
"            ")
        self.cardFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardFrame.setObjectName("cardFrame")
        self.cardLayout = QtWidgets.QVBoxLayout(self.cardFrame)
        self.cardLayout.setContentsMargins(40, 40, 40, 40)
        self.cardLayout.setSpacing(20)
        self.cardLayout.setObjectName("cardLayout")
        self.cardIconLabel = QtWidgets.QLabel(parent=self.cardFrame)
        self.cardIconLabel.setStyleSheet("font-size: 60px; background: transparent;")
        self.cardIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cardIconLabel.setObjectName("cardIconLabel")
        self.cardLayout.addWidget(self.cardIconLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.cardTitleLabel = QtWidgets.QLabel(parent=self.cardFrame)
        self.cardTitleLabel.setStyleSheet("color: #1a1a1a; font-size: 24px; font-weight: bold; background: transparent;")
        self.cardTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cardTitleLabel.setObjectName("cardTitleLabel")
        self.cardLayout.addWidget(self.cardTitleLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.cardDescLabel = QtWidgets.QLabel(parent=self.cardFrame)
        self.cardDescLabel.setWordWrap(True)
        self.cardDescLabel.setStyleSheet("color: #666; font-size: 14px; background: transparent;")
        self.cardDescLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cardDescLabel.setObjectName("cardDescLabel")
        self.cardLayout.addWidget(self.cardDescLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.cardPlayBtn = QtWidgets.QPushButton(parent=self.cardFrame)
        self.cardPlayBtn.setMinimumSize(QtCore.QSize(200, 45))
        self.cardPlayBtn.setStyleSheet("\n"
"QPushButton#cardPlayBtn {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #3f8bde, stop:1 #2968c0);\n"
"  border-radius: 10px;\n"
"  padding: 12px;\n"
"  font-size: 16px;\n"
"  font-weight: bold;\n"
"  color: white;\n"
"  border: none;\n"
"}\n"
"QPushButton#cardPlayBtn:hover {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #2968c0, stop:1 #1f4a8a);\n"
"}\n"
"QPushButton#cardPlayBtn:pressed {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #1f4a8a, stop:1 #142d5a);\n"
"}\n"
"              ")
        self.cardPlayBtn.setObjectName("cardPlayBtn")
        self.cardLayout.addWidget(self.cardPlayBtn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.homePageLayout.addWidget(self.cardFrame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.homePageLayout.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.homePageWidget)
        self.topicsPageWidget = QtWidgets.QWidget()
        self.topicsPageWidget.setObjectName("topicsPageWidget")
        self.topicsPageLayout = QtWidgets.QVBoxLayout(self.topicsPageWidget)
        self.topicsPageLayout.setContentsMargins(30, 20, 30, 20)
        self.topicsPageLayout.setSpacing(15)
        self.topicsPageLayout.setObjectName("topicsPageLayout")
        self.topicsHeaderLayout = QtWidgets.QHBoxLayout()
        self.topicsHeaderLayout.setObjectName("topicsHeaderLayout")
        self.backBtn = QtWidgets.QPushButton(parent=self.topicsPageWidget)
        self.backBtn.setMaximumSize(QtCore.QSize(120, 40))
        self.backBtn.setStyleSheet("\n"
"                    QPushButton#backBtn {\n"
"                      background: rgba(63, 139, 222, 0.2);\n"
"                      border-radius: 8px;\n"
"                      padding: 8px 16px;\n"
"                      font-size: 14px;\n"
"                      font-weight: bold;\n"
"                      color: #3f8bde;\n"
"                      border: 1px solid rgba(63, 139, 222, 0.3);\n"
"                    }\n"
"                    QPushButton#backBtn:hover {\n"
"                      background: rgba(63, 139, 222, 0.3);\n"
"                    }\n"
"                    QPushButton#backBtn:pressed {\n"
"                      background: rgba(63, 139, 222, 0.5);\n"
"                    }\n"
"              ")
        self.backBtn.setObjectName("backBtn")
        self.topicsHeaderLayout.addWidget(self.backBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topicsHeaderLayout.addItem(spacerItem4)
        self.topicsPageLayout.addLayout(self.topicsHeaderLayout)
        self.topicsHeaderLabel = QtWidgets.QLabel(parent=self.topicsPageWidget)
        self.topicsHeaderLabel.setStyleSheet("color: #1a1a1a; font-size: 22px; font-weight: bold; background: transparent;")
        self.topicsHeaderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.topicsHeaderLabel.setObjectName("topicsHeaderLabel")
        self.topicsPageLayout.addWidget(self.topicsHeaderLabel)
        self.topicsListWidget = QtWidgets.QListWidget(parent=self.topicsPageWidget)
        self.topicsListWidget.setStyleSheet("\n"
"                        QListWidget {\n"
"                          background: white;\n"
"                          border-radius: 10px;\n"
"                          border: 1px solid rgba(0, 0, 0, 0.1);\n"
"                          padding: 8px;\n"
"                        }\n"
"                        QListWidget::item {\n"
"                          padding: 4px;\n"
"                          border: none;\n"
"                          background: transparent;\n"
"                        }\n"
"                        QListWidget::item:hover {\n"
"                          background: transparent;\n"
"                        }\n"
"                        QListWidget::item:selected {\n"
"                          background: transparent;\n"
"                          color: #1a1a1a;\n"
"                        }\n"
"            ")
        self.topicsListWidget.setObjectName("topicsListWidget")
        self.topicsPageLayout.addWidget(self.topicsListWidget)
        self.stackedWidget.addWidget(self.topicsPageWidget)
        self.profilePageWidget = QtWidgets.QWidget()
        self.profilePageWidget.setObjectName("profilePageWidget")
        self.profileLayout = QtWidgets.QVBoxLayout(self.profilePageWidget)
        self.profileLayout.setSpacing(0)
        self.profileLayout.setObjectName("profileLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.profileLayout.addItem(spacerItem5)
        self.profileContentFrame = QtWidgets.QFrame(parent=self.profilePageWidget)
        self.profileContentFrame.setMinimumSize(QtCore.QSize(450, 0))
        self.profileContentFrame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.profileContentFrame.setObjectName("profileContentFrame")
        self.innerProfileLayout = QtWidgets.QVBoxLayout(self.profileContentFrame)
        self.innerProfileLayout.setSpacing(10)
        self.innerProfileLayout.setObjectName("innerProfileLayout")
        self.profileTitle = QtWidgets.QLabel(parent=self.profileContentFrame)
        self.profileTitle.setObjectName("profileTitle")
        self.innerProfileLayout.addWidget(self.profileTitle, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.usernameEdit = QtWidgets.QLineEdit(parent=self.profileContentFrame)
        self.usernameEdit.setObjectName("usernameEdit")
        self.innerProfileLayout.addWidget(self.usernameEdit)
        self.usernameErrors = QtWidgets.QLabel(parent=self.profileContentFrame)
        self.usernameErrors.setObjectName("usernameErrors")
        self.innerProfileLayout.addWidget(self.usernameErrors)
        self.emailEdit = QtWidgets.QLineEdit(parent=self.profileContentFrame)
        self.emailEdit.setObjectName("emailEdit")
        self.innerProfileLayout.addWidget(self.emailEdit)
        self.emailErrors = QtWidgets.QLabel(parent=self.profileContentFrame)
        self.emailErrors.setObjectName("emailErrors")
        self.innerProfileLayout.addWidget(self.emailErrors)
        self.passwordEdit = QtWidgets.QLineEdit(parent=self.profileContentFrame)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.innerProfileLayout.addWidget(self.passwordEdit)
        self.passwordErrors = QtWidgets.QLabel(parent=self.profileContentFrame)
        self.passwordErrors.setObjectName("passwordErrors")
        self.innerProfileLayout.addWidget(self.passwordErrors)
        self.confirmPasswordEdit = QtWidgets.QLineEdit(parent=self.profileContentFrame)
        self.confirmPasswordEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirmPasswordEdit.setObjectName("confirmPasswordEdit")
        self.innerProfileLayout.addWidget(self.confirmPasswordEdit)
        self.confirmErrors = QtWidgets.QLabel(parent=self.profileContentFrame)
        self.confirmErrors.setObjectName("confirmErrors")
        self.innerProfileLayout.addWidget(self.confirmErrors)
        self.saveProfileBtn = QtWidgets.QPushButton(parent=self.profileContentFrame)
        self.saveProfileBtn.setMinimumSize(QtCore.QSize(0, 55))
        self.saveProfileBtn.setObjectName("saveProfileBtn")
        self.innerProfileLayout.addWidget(self.saveProfileBtn)
        self.profileLayout.addWidget(self.profileContentFrame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.profileLayout.addItem(spacerItem6)
        self.stackedWidget.addWidget(self.profilePageWidget)
        self.settingsPageWidget = QtWidgets.QWidget()
        self.settingsPageWidget.setObjectName("settingsPageWidget")
        self.settingsPageWidget.setStyleSheet("QWidget#settingsPageWidget { background: #f7faff; }")
        self.settingsLayout = QtWidgets.QVBoxLayout(self.settingsPageWidget)
        self.settingsLayout.setContentsMargins(36, 28, 36, 28)
        self.settingsLayout.setSpacing(18)
        self.settingsLayout.setObjectName("settingsLayout")
        self.settingsHeroFrame = QtWidgets.QFrame(parent=self.settingsPageWidget)
        self.settingsHeroFrame.setObjectName("settingsHeroFrame")
        self.settingsHeroFrame.setStyleSheet("QFrame#settingsHeroFrame { background: qlineargradient(x1:0,y1:0,x2:1,y2:1, stop:0 #3f8bde, stop:1 #6fb6ff); border-radius: 22px; } QLabel { background: transparent; }")
        self.settingsHeroLayout = QtWidgets.QVBoxLayout(self.settingsHeroFrame)
        self.settingsHeroLayout.setContentsMargins(24, 22, 24, 22)
        self.settingsHeroLayout.setSpacing(8)
        self.settingsHeroLayout.setObjectName("settingsHeroLayout")
        self.settingsTitle = QtWidgets.QLabel(parent=self.settingsHeroFrame)
        self.settingsTitle.setObjectName("settingsTitle")
        self.settingsHeroLayout.addWidget(self.settingsTitle)
        self.settingsDescription = QtWidgets.QLabel(parent=self.settingsHeroFrame)
        self.settingsDescription.setWordWrap(True)
        self.settingsDescription.setObjectName("settingsDescription")
        self.settingsHeroLayout.addWidget(self.settingsDescription)
        self.settingsLayout.addWidget(self.settingsHeroFrame)
        self.midiSettingsFrame = QtWidgets.QFrame(parent=self.settingsPageWidget)
        self.midiSettingsFrame.setObjectName("midiSettingsFrame")
        self.midiSettingsFrame.setStyleSheet("QFrame#midiSettingsFrame { background: white; border-radius: 20px; border: 1px solid rgba(63, 139, 222, 0.14); } QLabel { background: transparent; } QComboBox#midiInputCombo { border: 1px solid rgba(63, 139, 222, 0.26); border-radius: 12px; padding: 10px 14px; min-height: 22px; background: #fdfefe; font-size: 14px; } QComboBox#midiInputCombo:hover { border-color: #3f8bde; } QPushButton#refreshMidiDevicesBtn, QPushButton#verifyMidiDeviceBtn { min-height: 42px; border-radius: 12px; font-size: 14px; font-weight: 700; padding: 0 16px; } QPushButton#refreshMidiDevicesBtn { background: rgba(63, 139, 222, 0.12); color: #2d6fbd; border: 1px solid rgba(63, 139, 222, 0.22); } QPushButton#refreshMidiDevicesBtn:hover { background: rgba(63, 139, 222, 0.18); } QPushButton#verifyMidiDeviceBtn { background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #3f8bde, stop:1 #2968c0); color: white; border: none; } QPushButton#verifyMidiDeviceBtn:hover { background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #2968c0, stop:1 #1f4a8a); }")
        self.midiSettingsLayout = QtWidgets.QVBoxLayout(self.midiSettingsFrame)
        self.midiSettingsLayout.setContentsMargins(24, 24, 24, 24)
        self.midiSettingsLayout.setSpacing(14)
        self.settingsCardAccent = QtWidgets.QLabel(parent=self.midiSettingsFrame)
        self.settingsCardAccent.setFixedHeight(6)
        self.settingsCardAccent.setStyleSheet("background: qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #3f8bde, stop:1 #77b6ff); border-radius: 3px;")
        self.midiSettingsLayout.addWidget(self.settingsCardAccent)
        self.settingsCardAccent.hide()
        self.midiSettingsLayout.setObjectName("midiSettingsLayout")
        self.settingsCardAccent.show()
        self.midiSettingsLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.midiButtonsRow = QtWidgets.QHBoxLayout()
        self.midiButtonsRow.setSpacing(10)
        self.midiButtonsRow.setObjectName("midiButtonsRow")
        self.midiSettingsTitle = QtWidgets.QLabel(parent=self.midiSettingsFrame)
        self.midiSettingsTitle.setObjectName("midiSettingsTitle")
        self.midiSettingsLayout.addWidget(self.midiSettingsTitle)
        self.midiSettingsHint = QtWidgets.QLabel(parent=self.midiSettingsFrame)
        self.midiSettingsHint.setWordWrap(True)
        self.midiSettingsHint.setObjectName("midiSettingsHint")
        self.midiSettingsLayout.addWidget(self.midiSettingsHint)
        self.midiInputCombo = QtWidgets.QComboBox(parent=self.midiSettingsFrame)
        self.midiInputCombo.setObjectName("midiInputCombo")
        self.midiSettingsLayout.addWidget(self.midiInputCombo)
        self.midiButtonsRow = QtWidgets.QHBoxLayout()
        self.midiButtonsRow.setObjectName("midiButtonsRow")
        self.refreshMidiDevicesBtn = QtWidgets.QPushButton(parent=self.midiSettingsFrame)
        self.refreshMidiDevicesBtn.setObjectName("refreshMidiDevicesBtn")
        self.midiButtonsRow.addWidget(self.refreshMidiDevicesBtn)
        self.verifyMidiDeviceBtn = QtWidgets.QPushButton(parent=self.midiSettingsFrame)
        self.verifyMidiDeviceBtn.setObjectName("verifyMidiDeviceBtn")
        self.midiButtonsRow.addWidget(self.verifyMidiDeviceBtn)
        self.midiSettingsLayout.addLayout(self.midiButtonsRow)
        self.midiSettingsStatusLabel = QtWidgets.QLabel(parent=self.midiSettingsFrame)
        self.midiSettingsStatusLabel.setWordWrap(True)
        self.midiSettingsStatusLabel.setObjectName("midiSettingsStatusLabel")
        self.midiSettingsLayout.addWidget(self.midiSettingsStatusLabel)
        self.settingsLayout.addWidget(self.midiSettingsFrame)
        spacerItem_settings = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.settingsLayout.addItem(spacerItem_settings)
        self.stackedWidget.addWidget(self.settingsPageWidget)
        self.adminPageWidget = QtWidgets.QWidget()
        self.adminPageWidget.setObjectName("adminPageWidget")
        self.adminLayout = QtWidgets.QVBoxLayout(self.adminPageWidget)
        self.adminLayout.setContentsMargins(30, 20, 30, 20)
        self.adminLayout.setSpacing(15)
        self.adminLayout.setObjectName("adminLayout")
        self.adminTitle = QtWidgets.QLabel(parent=self.adminPageWidget)
        self.adminTitle.setStyleSheet("color: #1a1a1a; font-size: 22px; font-weight: bold;")
        self.adminTitle.setObjectName("adminTitle")
        self.adminLayout.addWidget(self.adminTitle)
        self.adminTabWidget = QtWidgets.QTabWidget(parent=self.adminPageWidget)
        self.adminTabWidget.setStyleSheet("\n"
"             QTabBar::tab { padding: 10px 20px; font-size: 14px; font-weight: bold; background: #f0f0f0; border-top-left-radius: 8px; border-top-right-radius: 8px; margin-right: 2px; }\n"
"             QTabBar::tab:selected { background: white; color: #3f8bde; border-bottom: 2px solid white; }\n"
"             QTabWidget::pane { border: 1px solid #e0e0e0; background: white; border-radius: 10px; border-top-left-radius: 0px; }\n"
"            ")
        self.adminTabWidget.setObjectName("adminTabWidget")
        self.tab_topics = QtWidgets.QWidget()
        self.tab_topics.setObjectName("tab_topics")
        self.verticalLayout_tab_topics = QtWidgets.QVBoxLayout(self.tab_topics)
        self.verticalLayout_tab_topics.setObjectName("verticalLayout_tab_topics")
        self.topics_splitter = QtWidgets.QSplitter(parent=self.tab_topics)
        self.topics_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.topics_splitter.setObjectName("topics_splitter")
        self.topics_master_container = QtWidgets.QWidget(parent=self.topics_splitter)
        self.topics_master_container.setObjectName("topics_master_container")
        self.verticalLayout_master = QtWidgets.QVBoxLayout(self.topics_master_container)
        self.verticalLayout_master.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_master.setObjectName("verticalLayout_master")
        self.table_topics = QtWidgets.QTableWidget(parent=self.topics_master_container)
        self.table_topics.setObjectName("table_topics")
        self.table_topics.setColumnCount(3)
        self.table_topics.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_topics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_topics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_topics.setHorizontalHeaderItem(2, item)
        self.verticalLayout_master.addWidget(self.table_topics)
        self.addTopicLayout = QtWidgets.QHBoxLayout()
        self.addTopicLayout.setObjectName("addTopicLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.addTopicLayout.addItem(spacerItem7)
        self.btn_add_topic = QtWidgets.QPushButton(parent=self.topics_master_container)
        self.btn_add_topic.setObjectName("btn_add_topic")
        self.addTopicLayout.addWidget(self.btn_add_topic)
        self.verticalLayout_master.addLayout(self.addTopicLayout)
        self.lessons_detail_container = QtWidgets.QWidget(parent=self.topics_splitter)
        self.lessons_detail_container.setObjectName("lessons_detail_container")
        self.verticalLayout_detail = QtWidgets.QVBoxLayout(self.lessons_detail_container)
        self.verticalLayout_detail.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_detail.setObjectName("verticalLayout_detail")
        self.table_lessons = QtWidgets.QTableWidget(parent=self.lessons_detail_container)
        self.table_lessons.setObjectName("table_lessons")
        self.table_lessons.setColumnCount(2)
        self.table_lessons.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_lessons.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_lessons.setHorizontalHeaderItem(1, item)
        self.verticalLayout_detail.addWidget(self.table_lessons)
        self.addLessonLayout = QtWidgets.QHBoxLayout()
        self.addLessonLayout.setObjectName("addLessonLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.addLessonLayout.addItem(spacerItem8)
        self.btn_add_lesson = QtWidgets.QPushButton(parent=self.lessons_detail_container)
        self.btn_add_lesson.setEnabled(False)
        self.btn_add_lesson.setObjectName("btn_add_lesson")
        self.addLessonLayout.addWidget(self.btn_add_lesson)
        self.verticalLayout_detail.addLayout(self.addLessonLayout)
        self.verticalLayout_tab_topics.addWidget(self.topics_splitter)
        self.adminTabWidget.addTab(self.tab_topics, "")
        self.tab_users = QtWidgets.QWidget()
        self.tab_users.setObjectName("tab_users")
        self.verticalLayout_tab_users = QtWidgets.QVBoxLayout(self.tab_users)
        self.verticalLayout_tab_users.setObjectName("verticalLayout_tab_users")
        self.table_users = QtWidgets.QTableWidget(parent=self.tab_users)
        self.table_users.setObjectName("table_users")
        self.table_users.setColumnCount(4)
        self.table_users.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_users.setHorizontalHeaderItem(3, item)
        self.verticalLayout_tab_users.addWidget(self.table_users)
        self.adminTabWidget.addTab(self.tab_users, "")
        self.adminLayout.addWidget(self.adminTabWidget)
        self.stackedWidget.addWidget(self.adminPageWidget)
        self.verticalLayout_global.addWidget(self.mainSplitter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.adminTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music App — Главная"))
        self.userNameLabel.setText(_translate("MainWindow", "👤 Имя"))
        self.collapseBtn.setText(_translate("MainWindow", "◀"))
        self.collapseBtn.setToolTip(_translate("MainWindow", "Свернуть меню"))
        self.emailLabel.setText(_translate("MainWindow", "user@example.com"))
        self.homeBtn.setText(_translate("MainWindow", "🏠 Главная"))
        self.profileBtn.setText(_translate("MainWindow", "👤 Мой профиль"))
        self.settingsBtn.setText(_translate("MainWindow", "⚙️ Настройки"))
        self.adminPanelBtn.setText(_translate("MainWindow", "👤 Панель"))
        self.logoutBtn.setText(_translate("MainWindow", "🚪 Выйти"))
        self.cardIconLabel.setText(_translate("MainWindow", "🎵"))
        self.cardTitleLabel.setText(_translate("MainWindow", "Начни обучение"))
        self.cardDescLabel.setText(_translate("MainWindow", "Выбери интересующий тебя урок и начни свой путь в мире музыки"))
        self.cardPlayBtn.setText(_translate("MainWindow", "▶️ Играть по урокам"))
        self.backBtn.setText(_translate("MainWindow", "◀ Назад"))
        self.topicsHeaderLabel.setText(_translate("MainWindow", "📚 Доступные темы"))
        self.profileTitle.setText(_translate("MainWindow", "⚙️ Настройки профиля"))
        self.profileTitle.setStyleSheet(_translate("MainWindow", "font-size: 26px; font-weight: bold; margin-bottom: 20px; color: #1a1a1a;"))
        self.settingsTitle.setText(_translate("MainWindow", "⚙️ MIDI настройки"))
        self.settingsTitle.setStyleSheet(_translate("MainWindow", "font-size: 28px; font-weight: 800; color: white;"))
        self.settingsDescription.setText(_translate("MainWindow", "Выбери активный MIDI-вход для игры и проверь, что приложение действительно может открыть устройство."))
        self.settingsDescription.setStyleSheet(_translate("MainWindow", "color: rgba(255, 255, 255, 0.92); font-size: 14px;"))
        self.midiSettingsTitle.setText(_translate("MainWindow", "Подключённое MIDI-устройство"))
        self.midiSettingsTitle.setStyleSheet(_translate("MainWindow", "font-size: 20px; font-weight: 800; color: #1a1a1a;"))
        self.midiSettingsHint.setText(_translate("MainWindow", "Показываются только доступные сейчас MIDI-входы. Некоторые системы создают несколько портов для одного физического устройства."))
        self.midiSettingsHint.setStyleSheet(_translate("MainWindow", "color: #667085; font-size: 13px; line-height: 1.4;"))
        self.refreshMidiDevicesBtn.setText(_translate("MainWindow", "Обновить список устройств"))
        self.verifyMidiDeviceBtn.setText(_translate("MainWindow", "Проверить устройство"))
        self.midiSettingsStatusLabel.setText(_translate("MainWindow", "MIDI-устройство не выбрано"))
        self.midiSettingsStatusLabel.setStyleSheet(_translate("MainWindow", "color: #666; font-size: 13px;"))
        self.usernameEdit.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.usernameErrors.setStyleSheet(_translate("MainWindow", "color: #ff4444; font-size: 13px; margin-left: 10px;"))
        self.emailEdit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.emailErrors.setStyleSheet(_translate("MainWindow", "color: #ff4444; font-size: 13px; margin-left: 10px;"))
        self.passwordEdit.setPlaceholderText(_translate("MainWindow", "Новый пароль (если нужно)"))
        self.passwordErrors.setStyleSheet(_translate("MainWindow", "color: #ff4444; font-size: 13px; margin-left: 10px;"))
        self.confirmPasswordEdit.setPlaceholderText(_translate("MainWindow", "Подтверждение пароля"))
        self.confirmErrors.setStyleSheet(_translate("MainWindow", "color: #ff4444; font-size: 13px; margin-left: 10px;"))
        self.saveProfileBtn.setText(_translate("MainWindow", "Сохранить изменения"))
        self.saveProfileBtn.setStyleSheet(_translate("MainWindow", "\n"
"         QPushButton#saveProfileBtn {\n"
"           background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #3f8bde, stop:1 #2968c0);\n"
"           border-radius: 15px; color: white; font-size: 18px; font-weight: bold; margin-top: 10px;\n"
"         }\n"
"         QPushButton#saveProfileBtn:hover { background: #2968c0; }\n"
"        "))
        self.adminTitle.setText(_translate("MainWindow", "Панель администратора"))
        item = self.table_topics.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_topics.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название темы"))
        item = self.table_topics.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Уроков"))
        self.btn_add_topic.setText(_translate("MainWindow", "Добавить тему"))
        item = self.table_lessons.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_lessons.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название урока"))
        self.btn_add_lesson.setText(_translate("MainWindow", "Добавить урок"))
        self.adminTabWidget.setTabText(self.adminTabWidget.indexOf(self.tab_topics), _translate("MainWindow", "📚 Темы"))
        item = self.table_users.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_users.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Логин"))
        item = self.table_users.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.table_users.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Роль"))
        self.adminTabWidget.setTabText(self.adminTabWidget.indexOf(self.tab_users), _translate("MainWindow", "👥 Пользователи"))
