# Form implementation generated from reading ui file 'app/ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"  background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #3a8dde, stop:0.5 #00c8d6, stop:1 #2faf5e);\n"
"}\n"
"#drawerWidget {\n"
"  background: rgba(0,0,0,0.55);\n"
"  border-top-right-radius: 25px;\n"
"  border-bottom-right-radius: 25px;\n"
"}\n"
"#drawerWidget QPushButton {\n"
"  background: rgba(255,255,255,0.1);\n"
"  border-radius: 15px;\n"
"  padding: 10px;\n"
"  text-align: left;\n"
"  font-size: 16px;\n"
"  font-weight: 600;\n"
"  color: white;\n"
"}\n"
"#drawerWidget QPushButton:hover {\n"
"  background: rgba(255,255,255,0.25);\n"
"}\n"
"#drawerWidget QPushButton:pressed {\n"
"  background: rgba(255,255,255,0.4);\n"
"}\n"
"#drawerWidget QLabel {\n"
"  color: white;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"}\n"
"#drawerWidget #userNameLabel {\n"
"  font-size: 18px;\n"
"  font-weight: 700;\n"
"}\n"
"#collapseBtn {\n"
"  background: transparent;\n"
"  border: none;\n"
"  color: white;\n"
"  font-size: 20px;\n"
"  font-weight: bold;\n"
"}\n"
".lessonCard {\n"
"  background: rgba(255,255,255,0.92);\n"
"  border-radius: 20px;\n"
"  padding: 15px;\n"
"}\n"
".lessonCard QLabel {\n"
"  color: #222;\n"
"}\n"
".lessonCard QLabel:first-child {\n"
"  font-size: 22px;\n"
"  font-weight: 700;\n"
"  color: #1e8b1f;\n"
"}\n"
".lessonCard QPushButton {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #26af27, stop:1 #1a9f26);\n"
"  border-radius: 12px;\n"
"  padding: 8px;\n"
"  font-size: 14px;\n"
"  font-weight: bold;\n"
"  color: white;\n"
"}\n"
".lessonCard QPushButton:hover {\n"
"  background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 #1e8b1f, stop:1 #158015);\n"
"}\n"
"QScrollArea {\n"
"  background: transparent;\n"
"  border: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"  background: rgba(0,0,0,0.2);\n"
"  width: 10px;\n"
"  border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"  background: white;\n"
"  border-radius: 5px;\n"
"  min-height: 30px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"  height: 0px;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_global = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_global.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_global.setSpacing(0)
        self.verticalLayout_global.setObjectName("verticalLayout_global")
        self.mainSplitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mainSplitter.setChildrenCollapsible(False)
        self.mainSplitter.setObjectName("mainSplitter")
        self.drawerWidget = QtWidgets.QWidget(parent=self.mainSplitter)
        self.drawerWidget.setMinimumSize(QtCore.QSize(220, 0))
        self.drawerWidget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.drawerWidget.setObjectName("drawerWidget")
        self.verticalLayout_drawer = QtWidgets.QVBoxLayout(self.drawerWidget)
        self.verticalLayout_drawer.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_drawer.setSpacing(15)
        self.verticalLayout_drawer.setObjectName("verticalLayout_drawer")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout()
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        self.userNameLabel = QtWidgets.QLabel(parent=self.drawerWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.horizontalLayout_header.addWidget(self.userNameLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem)
        self.collapseBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.collapseBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.collapseBtn.setVisible(False)
        self.collapseBtn.setObjectName("collapseBtn")
        self.horizontalLayout_header.addWidget(self.collapseBtn)
        self.verticalLayout_drawer.addLayout(self.horizontalLayout_header)
        self.line_1 = QtWidgets.QFrame(parent=self.drawerWidget)
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout_drawer.addWidget(self.line_1)
        self.emailLabel = QtWidgets.QLabel(parent=self.drawerWidget)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout_drawer.addWidget(self.emailLabel)
        self.profileBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.profileBtn.setObjectName("profileBtn")
        self.verticalLayout_drawer.addWidget(self.profileBtn)
        self.settingsBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_drawer.addWidget(self.settingsBtn)
        self.logoutBtn = QtWidgets.QPushButton(parent=self.drawerWidget)
        self.logoutBtn.setObjectName("logoutBtn")
        self.verticalLayout_drawer.addWidget(self.logoutBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_drawer.addItem(spacerItem1)
        self.lessonsScrollArea = QtWidgets.QScrollArea(parent=self.mainSplitter)
        self.lessonsScrollArea.setWidgetResizable(True)
        self.lessonsScrollArea.setObjectName("lessonsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 720, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_scroll = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_scroll.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_scroll.setSpacing(20)
        self.verticalLayout_scroll.setObjectName("verticalLayout_scroll")
        self.greetingLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.greetingLabel.setStyleSheet("color: white; font-size: 28px; font-weight: bold; background: transparent;")
        self.greetingLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.greetingLabel.setObjectName("greetingLabel")
        self.verticalLayout_scroll.addWidget(self.greetingLabel)
        self.lessonsGridLayout = QtWidgets.QGridLayout()
        self.lessonsGridLayout.setSpacing(20)
        self.lessonsGridLayout.setObjectName("lessonsGridLayout")
        self.verticalLayout_scroll.addLayout(self.lessonsGridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_scroll.addItem(spacerItem2)
        self.lessonsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_global.addWidget(self.mainSplitter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music App — Главная"))
        self.userNameLabel.setText(_translate("MainWindow", "👤 Имя"))
        self.collapseBtn.setText(_translate("MainWindow", "◀"))
        self.collapseBtn.setToolTip(_translate("MainWindow", "Свернуть меню"))
        self.emailLabel.setText(_translate("MainWindow", "user@example.com"))
        self.profileBtn.setText(_translate("MainWindow", "👤 Мой профиль"))
        self.settingsBtn.setText(_translate("MainWindow", "⚙️ Настройки"))
        self.logoutBtn.setText(_translate("MainWindow", "🚪 Выйти"))
        self.greetingLabel.setText(_translate("MainWindow", "🎓 Выбери урок"))
